<#
.SYNOPSIS
    Audit Viewer - browse and view audit log CSV files from the dashboard logs/ folder.

.DESCRIPTION
    Standalone WPF tool for viewing audit log entries generated by the AVD Dashboard
    and Profile Tools. Reads daily CSV files (audit-YYYY-MM-DD.csv) from the logs/
    subfolder and displays them in a filterable, sortable DataGrid.

    Features:
      - Loads all audit CSV files from the logs/ folder
      - Date range picker to filter entries
      - Filter by Action type (dropdown)
      - Filter by User or Target (text search)
      - Sortable columns (click headers)
      - Export filtered view to CSV
      - Auto-refresh option

.NOTES
    Author        : virtualwebber (https://github.com/virtualwebber/AVD-Dashboard)
    Version       : 2026-03-23
    Requires      : PowerShell 5.1 or PowerShell 7 (Windows)

    DISCLAIMER:
    This script is provided as-is with no warranty, guarantee, or support of any kind.
    Use at your own risk. The author accepts no responsibility for any issues,
    data loss, or damages arising from the use of this script in any environment.
    Always test in a non-production environment before deploying.

    Version History:
    2026-03-23 - Initial release. DataGrid view, date filtering, action filter,
            text search, CSV export, auto-refresh.

#>

# =============================================================================
# Resolve the logs/ folder relative to this script (tools/ -> project root -> logs/)
# =============================================================================
$script:LogsFolder = Join-Path (Split-Path $PSScriptRoot -Parent) 'logs'

# =============================================================================
# Language mode check - WPF requires Full Language Mode
# =============================================================================
if ($ExecutionContext.SessionState.LanguageMode -ne 'FullLanguage') {
    $msg = "This tool requires PowerShell Full Language Mode to run.`n`n" +
           "Current mode: $($ExecutionContext.SessionState.LanguageMode)`n`n" +
           "This machine has a security policy (AppLocker/WDAC) that restricts PowerShell.`n" +
           "Please run this tool as Administrator."
    $wsh = New-Object -ComObject WScript.Shell
    $wsh.Popup($msg, 0, 'AVD Dashboard - Language Mode Restriction', 48) | Out-Null
    return
}

# =============================================================================
# WPF assemblies
# =============================================================================
Add-Type -AssemblyName PresentationFramework
Add-Type -AssemblyName PresentationCore
Add-Type -AssemblyName WindowsBase

# Set a unique AppUserModelID so the viewer appears as its own taskbar entry
try {
    $null = Add-Type -MemberDefinition @'
[DllImport("shell32.dll")]
public static extern int SetCurrentProcessExplicitAppUserModelID([MarshalAs(UnmanagedType.LPWStr)] string AppID);
'@ -Name 'Shell32AV' -Namespace 'Win32' -PassThru -ErrorAction Stop
    [Win32.Shell32AV]::SetCurrentProcessExplicitAppUserModelID('AVDAuditViewer') | Out-Null
} catch { <# non-critical #> }

# =============================================================================
# XAML - Window definition
# =============================================================================
$_icoPath = Join-Path $PSScriptRoot '..\data\avd-dashboard.ico'
# Use .ProviderPath for UNC-safe resolution (avoids FileSystem:: prefix)
$_icoAttr = if (Test-Path $_icoPath) { " Icon=`"$((Resolve-Path $_icoPath).ProviderPath)`"" } else { '' }

[xml]$xaml = @"
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="AVD Dashboard - Audit Viewer"
        Height="700" Width="1100"
        MinHeight="500" MinWidth="800"
        WindowStartupLocation="CenterScreen"$_icoAttr
        Background="#F4F6F9"
        FontFamily="Segoe UI"
        UseLayoutRounding="True"
        TextOptions.TextFormattingMode="Display"
        TextOptions.TextRenderingMode="ClearType">

    <Grid Margin="12">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="Auto"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>

        <!-- Header -->
        <TextBlock Grid.Row="0" Text="Audit Log Viewer" FontSize="18" FontWeight="Bold"
                   Foreground="#0078D4" Margin="0,0,0,10"/>

        <!-- Filter bar -->
        <Border Grid.Row="1" Background="#FFFFFF" CornerRadius="6" Padding="10"
                BorderBrush="#DDE1E7" BorderThickness="1" Margin="0,0,0,10">
            <WrapPanel Orientation="Horizontal" VerticalAlignment="Center">
                <TextBlock Text="Date From:" VerticalAlignment="Center" Margin="0,0,5,0"/>
                <DatePicker x:Name="DateFrom" Width="130" Margin="0,0,12,0"/>

                <TextBlock Text="Date To:" VerticalAlignment="Center" Margin="0,0,5,0"/>
                <DatePicker x:Name="DateTo" Width="130" Margin="0,0,12,0"/>

                <TextBlock Text="Action:" VerticalAlignment="Center" Margin="0,0,5,0"/>
                <ComboBox x:Name="ActionFilter" Width="140" Margin="0,0,12,0">
                    <ComboBoxItem Content="All Actions" IsSelected="True"/>
                </ComboBox>

                <TextBlock Text="Search:" VerticalAlignment="Center" Margin="0,0,5,0"/>
                <TextBox x:Name="SearchBox" Width="180" Margin="0,0,12,0"
                         VerticalContentAlignment="Center" Padding="4,2"/>

                <Button x:Name="RefreshBtn" Content="Refresh" Width="75" Height="28"
                        Background="#0078D4" Foreground="White" BorderThickness="0"
                        Cursor="Hand" Margin="0,0,6,0"/>
                <Button x:Name="ExportBtn" Content="Export" Width="75" Height="28"
                        Background="#107C10" Foreground="White" BorderThickness="0"
                        Cursor="Hand"/>
            </WrapPanel>
        </Border>

        <!-- DataGrid -->
        <DataGrid Grid.Row="2" x:Name="AuditGrid"
                  AutoGenerateColumns="False"
                  IsReadOnly="True"
                  CanUserSortColumns="True"
                  SelectionMode="Extended"
                  SelectionUnit="FullRow"
                  HeadersVisibility="Column"
                  GridLinesVisibility="Horizontal"
                  HorizontalGridLinesBrush="#E8E8E8"
                  AlternatingRowBackground="#F8F9FB"
                  BorderBrush="#DDE1E7"
                  BorderThickness="1"
                  FontSize="12.5">
            <DataGrid.ColumnHeaderStyle>
                <Style TargetType="DataGridColumnHeader">
                    <Setter Property="Background" Value="#0078D4"/>
                    <Setter Property="Foreground" Value="White"/>
                    <Setter Property="FontWeight" Value="SemiBold"/>
                    <Setter Property="Padding" Value="8,5"/>
                    <Setter Property="BorderBrush" Value="#005A9E"/>
                    <Setter Property="BorderThickness" Value="0,0,1,0"/>
                </Style>
            </DataGrid.ColumnHeaderStyle>
            <DataGrid.Columns>
                <DataGridTextColumn Header="Timestamp" Binding="{Binding Timestamp}" Width="150"/>
                <DataGridTextColumn Header="User" Binding="{Binding User}" Width="200"/>
                <DataGridTextColumn Header="Action" Binding="{Binding Action}" Width="120"/>
                <DataGridTextColumn Header="Target" Binding="{Binding Target}" Width="200"/>
                <DataGridTextColumn Header="Details" Binding="{Binding Details}" Width="*"/>
                <DataGridTextColumn Header="Result" Binding="{Binding Result}" Width="100"/>
            </DataGrid.Columns>
        </DataGrid>

        <!-- Status bar -->
        <Border Grid.Row="3" Background="#0078D4" CornerRadius="0,0,6,6" Padding="10,6" Margin="0,6,0,0">
            <Grid>
                <TextBlock x:Name="StatusText" Text="Ready" Foreground="White" FontSize="12"
                           HorizontalAlignment="Left" VerticalAlignment="Center"/>
                <TextBlock x:Name="CountText" Text="" Foreground="White" FontSize="12"
                           HorizontalAlignment="Right" VerticalAlignment="Center"/>
            </Grid>
        </Border>
    </Grid>
</Window>
"@

# =============================================================================
# Build the WPF window
# =============================================================================
$reader = [System.Xml.XmlNodeReader]::new($xaml)
$window = [System.Windows.Markup.XamlReader]::Load($reader)

$DateFrom     = $window.FindName("DateFrom")
$DateTo       = $window.FindName("DateTo")
$ActionFilter = $window.FindName("ActionFilter")
$SearchBox    = $window.FindName("SearchBox")
$RefreshBtn   = $window.FindName("RefreshBtn")
$ExportBtn    = $window.FindName("ExportBtn")
$AuditGrid    = $window.FindName("AuditGrid")
$StatusText   = $window.FindName("StatusText")
$CountText    = $window.FindName("CountText")

# Default date range: last 7 days
$DateFrom.SelectedDate = (Get-Date).AddDays(-7)
$DateTo.SelectedDate   = (Get-Date)

# =============================================================================
# Data loading and filtering
# =============================================================================

# All loaded audit entries (unfiltered)
$script:allEntries = [System.Collections.Generic.List[PSCustomObject]]::new()

# Known action types for the dropdown
$script:knownActions = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

function Load-AuditData {
    $script:allEntries.Clear()
    $script:knownActions.Clear()

    if (-not (Test-Path $script:LogsFolder)) {
        $StatusText.Text = "Logs folder not found: $($script:LogsFolder)"
        return
    }

    # Find all audit CSV files in the logs/ folder
    $csvFiles = Get-ChildItem -Path $script:LogsFolder -Filter 'audit-*.csv' -File -ErrorAction SilentlyContinue |
                Sort-Object Name

    if ($csvFiles.Count -eq 0) {
        $StatusText.Text = "No audit log files found in $($script:LogsFolder)"
        return
    }

    $totalRows = 0
    foreach ($file in $csvFiles) {
        try {
            # Import-Csv handles quoted fields and header row automatically
            $rows = Import-Csv -Path $file.FullName -ErrorAction Stop
            foreach ($row in $rows) {
                $script:allEntries.Add($row)
                if ($row.Action) { [void]$script:knownActions.Add($row.Action) }
                $totalRows++
            }
        } catch {
            # Skip malformed files silently
        }
    }

    # Rebuild the Action filter dropdown with discovered action types
    $ActionFilter.Items.Clear()
    $allItem = [System.Windows.Controls.ComboBoxItem]::new()
    $allItem.Content = 'All Actions'
    $ActionFilter.Items.Add($allItem) | Out-Null
    foreach ($action in ($script:knownActions | Sort-Object)) {
        $item = [System.Windows.Controls.ComboBoxItem]::new()
        $item.Content = $action
        $ActionFilter.Items.Add($item) | Out-Null
    }
    $ActionFilter.SelectedIndex = 0

    $StatusText.Text = "Loaded $totalRows entries from $($csvFiles.Count) file(s)"
}

function Apply-Filters {
    $filtered = [System.Collections.Generic.List[PSCustomObject]]::new()

    $fromDate = $DateFrom.SelectedDate
    $toDate   = $DateTo.SelectedDate
    # Add one day to "to" date so entries on that day are included
    if ($toDate) { $toDate = $toDate.AddDays(1) }

    $actionVal = if ($ActionFilter.SelectedItem) { $ActionFilter.SelectedItem.Content } else { 'All Actions' }
    $searchVal = $SearchBox.Text.Trim()

    foreach ($entry in $script:allEntries) {
        # Date filter - parse the timestamp from the CSV entry
        $entryDate = $null
        if ($entry.Timestamp) {
            try { $entryDate = [DateTime]$entry.Timestamp } catch {}
        }
        if ($fromDate -and $entryDate -and $entryDate -lt $fromDate) { continue }
        if ($toDate   -and $entryDate -and $entryDate -ge $toDate)   { continue }

        # Action filter
        if ($actionVal -ne 'All Actions' -and $entry.Action -ne $actionVal) { continue }

        # Text search - matches against User, Target, or Details
        if ($searchVal) {
            $match = ($entry.User    -and $entry.User    -like "*$searchVal*") -or
                     ($entry.Target  -and $entry.Target  -like "*$searchVal*") -or
                     ($entry.Details -and $entry.Details -like "*$searchVal*")
            if (-not $match) { continue }
        }

        $filtered.Add($entry)
    }

    # Sort newest first
    # Sort newest first
    $sorted = $filtered | Sort-Object {
        try { [DateTime]$_.Timestamp } catch { [DateTime]::MinValue }
    } -Descending

    $AuditGrid.ItemsSource = @($sorted)
    $CountText.Text = "$($filtered.Count) of $($script:allEntries.Count) entries"
}

# =============================================================================
# Event handlers
# =============================================================================

$RefreshBtn.Add_Click({
    Load-AuditData
    Apply-Filters
})

# Apply filters when any filter control changes
$DateFrom.Add_SelectedDateChanged({ Apply-Filters })
$DateTo.Add_SelectedDateChanged({ Apply-Filters })
$ActionFilter.Add_SelectionChanged({ Apply-Filters })

# Debounced text search - apply on each keystroke
$SearchBox.Add_TextChanged({ Apply-Filters })

# Export filtered data to CSV
$ExportBtn.Add_Click({
    $dlg = New-Object Microsoft.Win32.SaveFileDialog
    $dlg.Filter   = "CSV Files (*.csv)|*.csv"
    $dlg.FileName = "audit-export-$(Get-Date -Format 'yyyy-MM-dd')"
    if ($dlg.ShowDialog()) {
        try {
            $items = @($AuditGrid.ItemsSource)
            if ($items.Count -eq 0) {
                [System.Windows.MessageBox]::Show("No data to export.", "Export", "OK", "Information") | Out-Null
                return
            }
            $items | Select-Object Timestamp, User, Action, Target, Details, Result |
                Export-Csv -Path $dlg.FileName -NoTypeInformation -Force
            $StatusText.Text = "Exported $($items.Count) entries to: $($dlg.FileName)"
        } catch {
            [System.Windows.MessageBox]::Show("Export failed:`n$_", "Export Error", "OK", "Error") | Out-Null
        }
    }
})

# =============================================================================
# Initial data load and show
# =============================================================================
Load-AuditData
Apply-Filters

$window.ShowDialog() | Out-Null
